<img src="Figs/Cab_IF_Red_01.png" alt="drawing" width="80%"/>


<!--

<img href="Figs/Cab_IF_Red_01.png" style="width: 80%;" /> doesn't work

![Logotipo do IF](../Figs/Cab_IF_Red_01.png){ width=50% }

<h1> <span style="color:blue">Curso de Python</span> </h1> 
-->

<p style="margin-bottom:1cm;"> </p>


<center> <font size="6" color="blue">Curso de Python</font> </center>


<font size="4" color="blue">**Prof. :** Salviano A. Leão -- Instituto de Física - UFG-GO</font>


Python Numérico (numpy): arrays
================================

Introdução a biblioteca Numpy
------------------

A biblioteca NumPy (leia como *NUMerical PYthon*) fornece acesso a

- uma nova estrutura de dados chamada `array`s que permite:

    - operações vetoriais e matriciais eficientes. Também fornece

    - um número de operações de álgebra linear (tais como a resolução de sistemas de equações lineares, computação de autovetore e autovalores (Eigenvectors e Eigenvalues)).

- [NumPy: creating and manipulating numerical data](http://www.scipy-lectures.org/intro/numpy/numpy.html)


### História

Algumas informações de segundo plano: Existem duas outras implementações que fornecem quase a mesma funcionalidade cda NumPy. Estes são chamados de "numérico" e "numarray":

- Numeric foi a primeira provisão de um conjunto de métodos numéricos (semelhante ao Matlab) para Python. Ele evoluiu de um projeto de doutorado.

- Numarray é uma re-implementação de Numeric com certas melhorias (mas para os nossos propósitos Numérico e Numarray se comportam praticamente idênticos).

- No início de 2006, decidiu-se combinar os melhores aspectos de Numeric e Numarray no pacote Scientific Python (<span>`scipy`</span>) e fornecer um tipo de dados `array` Nome do módulo "NumPy".

Usaremos nos seguintes materiais o pacote "NumPy" fornecido pelo (novo) SciPy. Se por alguma razão isso não funcionar para você, as chances são de que seu SciPy seja muito velho. Nesse caso, você encontrará que "Numeric" ou "numarray" está instalado e deve fornecer quase as mesmas capacidades. [5]

### Matrizes (arrays)

Introduzimos um novo tipo de dados (fornecido por NumPy) que é chamado de `array`. Uma matriz *surge* de forma muito semelhante a uma lista, mas uma matriz pode manter apenas elementos do mesmo tipo (enquanto uma lista pode misturar diferentes tipos de objetos). Isso significa que os *arrays* são mais eficientes para armazenar (porque não precisamos armazenar o tipo para cada elemento). Isso também torna as matrizes (*arrays*) como sendo a estrutura de dados a ser escolhida para cálculos numéricos onde muitas vezes lidamos com vetores e matrizes.


A principal diferença com as listas é que as matrizes no numpy são de um tipo só ou seja, nas listas da para misturar string, inteiros, reais, complexos, etc, o que você bem entender; já nos vetores do numpy você só pode usar objetos de um mesmo tipo ou inteiros, ou reais ou complexos (sendo que cada um deles pode ser de diversas precisões, como se mostra na tabela embaixo) 


|          Tipo         |                                    Descrição                                    |
|-----------------------|---------------------------------------------------------------------------------|
| bool                  | verdadeiro ou Falso, 1 bit                                                      |
| int8                  | Byte ($-128$ a $127$)                                                           |
| int16                 | Inteiro ($-32768$ a $32767$)                                                    |
| int32                 | Inteiro $\left(2\times10^{31}\right.$ a $\left.2\times10^{31}-1\right)$         |
| int64                 | Inteiro $\left(2\times10^{63}\right.$ a $\left.2\times10^{63}-1\right)$         |
| uint8                 | Byte ($0$ a $255$)                                                              |
| uint16                | Inteiro ($0$ a $65535$)                                                         |
| uint32                | Inteiro $\left(0\right.$ a $\left.2\times10^{32}-1\right)$                      |
| uint64                | Inteiro $\left(0\right.$ a $\left.2\times10^{64}-1\right)$                      |
| float16               | real de precisão média: bit de sinal, expoente de 5 bits e 10 bits de mantisa   |
| float32               | real de precisão simples: bit de sinal, expoente de 8 bits e 23 bits de mantisa |
| float64 ou float      | real de precisão dupla: bit de sinal, expoente de 11 bits e 52 bits de mantisa  |
| complex64             | número complexo formado por 2 float32 - parte real e imaginaria                 |
| complex128 ou complex | número complexo formado por 2 float64 - parte real e imaginaria                 |



## Os objetos fundamentais NumPy

Toda a funcionalidade da computação científica da NumPy e da SciPy é construída em torno de dois tipos básicos de objetos da NumPy. O primeiro objeto é uma matriz n-dimensional conhecida como ndarray, e o segundo objeto é uma função universal chamada ufunc. Além destes dois objetos, há um número de outros objetos construídos em cima deles.

### O objeto ndarray

O objeto ndarray é uma coleção homogênea de elementos que são indexados usando N inteiros, onde N é a dimensão da matriz. Existem dois atributos importantes de ndarray. O primeiro é o tipo de dados dos elementos da matriz, chamado dtype, eo segundo é a forma da matriz. O tipo de dados aqui pode ser qualquer tipo de dados suportado pelo Python. A forma dos arrays é uma N-tupla, ou seja, uma coleção de N elementos para a matriz N-dimensional, onde cada elemento da tupla define o número de elementos nessa dimensão da matriz.


#### Operações com vetores no numpy

Vejamos algumas das operações, elemento a elemento que podem ser feitas sobre vetores numpy. Se você vai usar algum desse métodos lembre-se que devemos escrever numpy.metodo onde método é alguma das operações que são descrita a seguir:

**Operações sobre matrizes numpy**


**Definição dos elementos da matriz**

|         Método            |                                Resultado                                        |
|:--------------------------|:--------------------------------------------------------------------------------|
| zeros((N,M))              | vetor com zeros, M linhas, N colunas                                            |
| ones((M,N))               | vetor com uns, $M\times N$                                                      |
| empty((M,N))              | vetor vazio (qualquer valor), $M\times N$                                       |
|                           |                                                                                 |
| zeros_like(A)             | vetor com zeros, formato do A.                                                  |
| ones_like(A)              | vetor com uns, formato do A.                                                    |
| empty_like(A)             | vetor vazio, formato do A.                                                      |
|                           |                                                                                 |
| random.random((M,N))      | vetor com números aleatórios, $M\times N$                                       |
| identity(N,float)         | matriz identidade $N\times N$, ponto flutuante                                  |
| array([(1.5,2,3),(4,5,6)])| especifica os valores da matriz                                                 |
| mgrid[1:3,2:5]            | grade retangular x=[1,2] e y=[2,3,4]                                            |
|                           |                                                                                 |
| fromfunction(f, (M,N))    | matriz calculada com função f(i,j), $M\times N$                                 |
| arange(I, F, P)           | vetor com inicio I, fim F, passo P                                              |
| linspace(I,F,N)           | vetor com N números de I até F                                                  |

**Operações sobre matrizes numpy**


|         Método            |                                Resultado                                        |
|:--------------------------|:--------------------------------------------------------------------------------|
| A.sum()                   | soma dos itens                                                                  |
| A.min()                   | valor mínimo                                                                    |
| A.max()                   | valor máximo                                                                    |
| A.mean()                  | média aritmética                                                                |
| A.std()                   | desvio padrão                                                                   |
| A.var()                   | variância                                                                       |
| A.trace()                 | traço                                                                           |
| A.size()                  | número de elementos                                                             |
| A.shape()                 | formato                                                                         |
| A.ptp()                   | pico-a-pico (máximo - mínimo)                                                   |
| A.ravel()                 | versão 1D                                                                       |
| A.transpose(), A.T        | matriz transposta                                                               |
| A.resize(M,N)             | reforma ou trunca a matriz in situ                                              |
| A.reshape(M,N)            | retorna matriz com novo formato                                                 |
| A.clip(Amin,Amax)         | corta valores em Amin e Amax                                                    |
| A.compress(condição)      | seleciona elementos baseado em condição                                         |
| A.conjugate()             | complexo conjugado                                                              |
| A.copy()                  | retorna copia                                                                   |
| A.fill(valor)             | preenche com valor                                                              |



**Definição dos elementos da matriz**

|         Método            |                                Resultado                                        |
|:--------------------------|:--------------------------------------------------------------------------------|
| zeros((N,M))              | vetor com zeros, M linhas, N colunas                                            |
| ones((M,N))               | vetor com uns, $M\times N$                                                      |
| empty((M,N))              | vetor vazio (qualquer valor), $M\times N$                                       |
|                           |                                                                                 |
| zeros_like(A)             | vetor com zeros, formato do A.                                                  |
| ones_like(A)              | vetor com uns, formato do A.                                                    |
| empty_like(A)             | vetor vazio, formato do A.                                                      |
|                           |                                                                                 |
| random.random((M,N))      | vetor com números aleatórios, $M\times N$                                       |
| identity(N,float)         | matriz identidade $N\times N$, ponto flutuante                                  |
| array([(1.5,2,3),(4,5,6)])| especifica os valores da matriz                                                 |
| mgrid[1:3,2:5]            | grade retangular x=[1,2] e y=[2,3,4]                                            |
|                           |                                                                                 |
| fromfunction(f, (M,N))    | matriz calculada com função f(i,j), $M\times N$                                 |
| arange(I, F, P)           | vetor com inicio I, fim F, passo P                                              |
| linspace(I,F,N)           | vetor com N números de I até F                                                  |

**Operações sobre matrizes numpy**


|         Método            |                                Resultado                                        |
|:--------------------------|:--------------------------------------------------------------------------------|
| A.sum()                   | soma dos itens                                                                  |
| A.min()                   | valor mínimo                                                                    |
| A.max()                   | valor máximo                                                                    |
| A.mean()                  | média aritmética                                                                |
| A.std()                   | desvio padrão                                                                   |
| A.var()                   | variância                                                                       |
| A.trace()                 | traço                                                                           |
| A.size()                  | número de elementos                                                             |
| A.shape()                 | formato                                                                         |
| A.ptp()                   | pico-a-pico (máximo - mínimo)                                                   |
| A.ravel()                 | versão 1D                                                                       |
| A.transpose(), A.T        | matriz transposta                                                               |
| A.resize(M,N)             | reforma ou trunca a matriz in situ                                              |
| A.reshape(M,N)            | retorna matriz com novo formato                                                 |
| A.clip(Amin,Amax)         | corta valores em Amin e Amax                                                    |
| A.compress(condição)      | seleciona elementos baseado em condição                                         |
| A.conjugate()             | complexo conjugado                                                              |
| A.copy()                  | retorna copia                                                                   |
| A.fill(valor)             | preenche com valor                                                              |


|         Método              |                                Resultado                                            |
|:----------------------------|:------------------------------------------------------------------------------------|
| C = A-B, C=A+B, C=A*B,      | operações elemento a elemento, por exemplo: $\left(C_{ij}=A_{ij}-B_{ij}\right)$     |     
| C=A/B, `A**2`               | operações elemento a elemento                                                       |                 
|                             |                                                                                     |                                                                                             
| dot(A,B), mat(A)*mat(B)     | produto matricial                                                                   |                   
| inner(A, B)                 | produto interno                                                                     |                   
| outer(A, B)                 | produto externo                                                                     |                   
| concatenate(arrays, axis=0) | concatena vetores                                                                   |                 
| vstack(A,B)                 | empilha verticalmente vetores                                                       |                   
| hstack(A,B)                 | empilha horizontalmente vetores                                                     |                   
| vsplit(A,2)                 | parte verticalmente vetor                                                           |
| hsplit(A,2)                 | parte horizontalmente vetor                                                         |                  
|                             |                                                                                     |   
| A[0]                        | primeiro elemento                                                                   |                   
| A[i][j], A[i,j]             | convenção dos índices $A_{ij}$, (linha $i$, coluna $j$)                             |           
| A[3][2]                     | $A_{32}$ $3^{\underline{o}}$ elemento na $4^{\underline{a}}$ linha                  |           
| A[1]                        | $2^{\underline{a}}$ linha                                                           |                   
|                             |                                                                                     |              
| x[2]                        | $3^{\underline{o}}$ elemento                                                        |                   
| x[-2]                       | penúltimo elemento (índice contando do fim)                                         |                   
| x[2:5]                      | subvetor que vai do  $3^{\underline{o}}$ até o $5^{\underline{o}}$: $\left[x[2],\,x[3],\,x[4]\right]$ | 
| x[:5]                       | elementos desde x[0] até x[4]                                                       |                   
| x[2:]                       | do terceiro elemento até o fim                                                      |                   
| x[:]                        | todo o vetor                                                                        |                   
| x[2:9:3]                    | do terceiro até o decimo elemento de, três em três: $\left[ x[2],\,x[5],\,x[8]\right]$                 |
| x[numpy.where(x>7)]         | elementos em x maiores que 7                                                        |                 




vejamos alguns exemplos, para definirmos uma matriz ou um vetor existem diversas forma: 




### Os atributos de uma matriz

Além da forma e dtype, os outros atributos importantes de um array são os seguintes:

- `size`
- `itemsize`
- `data`
- `ndim`

O `itemsize` é o comprimento de um elemento da matriz em bytes e o atributo `data` é um objeto de buffer Python que aponta para o início dos dados da matriz. Vamos entender o conceito de forma, tipo de dados e outros atributos com a ajuda do seguinte programa Python:

In [1]:
import numpy as np
x2d = np.array( (
                 (100,200,300.0),
                 (111,222,333),
                 (123,456,789) ) )
print('x2d.shape = ',x2d.shape)
print('x2d.dtype = ',x2d.dtype)
print('x2d.size = ',x2d.size)
print('x2d.itemsize = ',x2d.itemsize)
print('x2d.ndim = ',x2d.ndim)
print('x2d.data = ',x2d.data)

x2d.shape =  (3, 3)
x2d.dtype =  float64
x2d.size =  9
x2d.itemsize =  8
x2d.ndim =  2
x2d.data =  <memory at 0x7ff72b27e1f8>


In [ ]:
import math
print(np.sin(x2d))
print()
for i in range(3):
    print(math.sin(x2d[i,0]),math.sin(x2d[i,1]),math.sin(x2d[0,2]))

In [2]:
import numpy as np
import math
n=10000

In [3]:
%%timeit 
for x in range(n): 
    math.sin(x)

1.13 ms ± 35 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%%timeit
x=np.linspace(1,n,n)
np.sin(x)

281 µs ± 3.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
y2d=np.array( [
                 (110,210,310),
                 (101,202,303),
                 (120,450,780) ] )

In [6]:
x = x2d+y2d
print(x)
type(x)

[[ 210.  410.  610.]
 [ 212.  424.  636.]
 [ 243.  906. 1569.]]


numpy.ndarray

In [7]:
m1 = np.dot(x2d,y2d)
m2 = np.mat(x2d) * np.mat(y2d)
c = m1 - m2
print(m1)
print()
print(c)

[[ 67200. 196400. 325600.]
 [ 74592. 218004. 361416.]
 [154266. 472992. 791718.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Vetores e matrizes (e matrizes com mais de dois índices) são todos chamados "arrays" em NumPy.

#### Vectores (1d-arrays)

A estrutura de dados que precisamos mais frequentemente é um vetor. Aqui estão alguns exemplos de como podemos gerar um:

- Conversão de uma lista (ou tupla) em uma matriz usando <span>`numpy.array`</span>:

In [8]:
import numpy as np
x = np.array([0, 0.5, 1, 1.5, 2])
print('x.dtype = ',x.dtype)
print(x)

x.dtype =  float64
[0.  0.5 1.  1.5 2. ]


In [9]:
# Lista
L = [1, 2, 4, 5, 8]
print(L)
print(np.array(L))

[1, 2, 4, 5, 8]
[1 2 4 5 8]


Criando linhas:

In [10]:
x = np.array([[0], [0.5], [1], [1.5], [2]])
print('x.dtype = ',x.dtype)
print(x)

x.dtype =  float64
[[0. ]
 [0.5]
 [1. ]
 [1.5]
 [2. ]]


In [ ]:
# Para ver toda as possibilidades de array
help(np.array)

-   Criação de um vetor usando “Array RANGE”:

In [11]:
y0 = 0.0   # Ponto inicial
yf = 2.5   # Ponto final
Np = 6     # Número de pontos
y = np.linspace(y0,yf,Np) 
print(y)

[0.  0.5 1.  1.5 2.  2.5]


In [12]:
x0 = 0.0   # Ponto inicial
xf = 2.5   # Ponto final
passo = 0.25     # Passo 
x = np.arange(x0, xf, passo)
print(x)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25]


Criando linhas:

In [13]:
x = np.array([x])

y=np.transpose(x)
y

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ],
       [1.25],
       [1.5 ],
       [1.75],
       [2.  ],
       [2.25]])

-   Criação de vetores com zeros

In [14]:
x = np.zeros((4,4))
print('x = ',x,'\n')
y=np.ones((4,4))
print('y = ',y,'\n')
I=np.identity(4)
print('I = ', I,'\n')
I[0][3]= -7
I[3,0] = 5  # Essa referência pode ter problema
print('I1 = ', I,'\n')
print('I1^t = ', np.transpose(I))

x =  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

y =  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

I =  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

I1 =  [[ 1.  0.  0. -7.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 5.  0.  0.  1.]] 

I1^t =  [[ 1.  0.  0.  5.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-7.  0.  0.  1.]]


In [15]:
I[0,3], I[3,0]

(-7.0, 5.0)

O tipo de referência abaixo vem da linguagem C.

In [17]:
I[0][3], I[3][0]

(-7.0, 5.0)

Uma vez estabelecida a matriz, podemos definir e recuperar valores individuais. Por exemplo:

In [24]:
n = 8
L=[2*i+1 for i in range(0,n)]
print(L)

[1, 3, 5, 7, 9, 11, 13, 15]


In [32]:
x = np.array(L)
print(x)

[ 1  3  5  7  9 11 13 15]


In [37]:
print(x)
print(x[0])
print(x[0:-1])
print(x[0:-7])

[ 1  3  5  7  9 11 13 15]
1
[ 1  3  5  7  9 11 13]
[1]


In [36]:
x[-2]

13

Essa característica de fatiamento foi herdada do fortran

In [39]:
x[1:n//2+1] = 5

In [ ]:
print(x)

In [ ]:
for i in range(1,n//2+1):
    x[i] = 7
print(x)

## Diferença entre funções

In [ ]:
import math

In [ ]:
x[1:n//2+1] = math.sin(math.pi/3)

In [ ]:
print(x)

In [ ]:
# cosidere o vetor y
n=9
x = np.ones(n)
#y = np.zeros(n)
for i in range(n):
    x[i] = ((math.pi)/(n-1))*i

In [ ]:
%%timeit 
y = np.sin(x)

In [ ]:
print(x,y)

In [ ]:
y = math.sin(x)

Para usa a math, deve-se implementar um loop

In [ ]:
y =np.zeros(n)

In [ ]:
%%timeit
for i in range(n):
    y[i] = math.sin(x[i])

In [ ]:
print(y)

Observe que uma vez que temos um vetor podemos realizar cálculos em cada elemento no vetor com uma única declaração:

In [ ]:
x = np.arange(0, 2.5, 0.5)
print(x)
print(x + 10)
print(x ** 2)
print(np.sin(x))

As funções intrínsecas da numpy conseguem atuar sobre os elementos dos arrays enquanto da da math não. Observe que 

In [ ]:
import math 
print(math.sin(x))

In [ ]:
x=np.arange(9)
print(x)

In [ ]:
np.reshape?

In [ ]:
y=x.reshape(3,3)
print(y)

In [ ]:
x=np.arange(-3,6,1).reshape((3,3))
x

In [ ]:
np.exp(-x)

In [ ]:
math.exp(-x)

In [ ]:
math.exp(-x[0,0])

#### Matrizes (arrays-2d)

Aqui estão duas maneiras de criar uma matriz 2d:

- Por converter uma lista de listas (ou tuplas) em uma matriz:

In [44]:
L=[1, 3, 5, 8, 9.0, 7]
print(type(L))

<class 'list'>


In [45]:
y = np.array(L)
print(y)

[1. 3. 5. 8. 9. 7.]


In [ ]:
x = list(y)
print(x)

In [ ]:
x = np.array(([1, 2, 3], [4, 5, 6], [9, 7, 8]))
x

-   Usando o método <span> `zeros` </span> para criar uma matriz com 5 linhas e 4 colunas

In [ ]:
x = np.zeros((5, 4))
x

A "forma" de uma matriz pode ser consultada como este (aqui temos 2 linhas e 3 colunas):

In [ ]:
x=np.array([[1, 2, 3], [4, 5, 6]])
print(x)
x.shape

Elementos individuais podem ser acessados e definidos usando esta sintaxe:

In [ ]:
x=np.array([[1, 2, 3], [4, 5, 6]])
print(x)
x[0, 0] 

In [ ]:
x[0, 1]

In [ ]:
x[0][1]

In [ ]:
x[0, 2]

In [ ]:
x[1, 0]

In [ ]:
x[:, 0]

In [ ]:
x[0,:]

### Converter uma matriz em uma lista ou tupla

Para criar uma matriz e converte-la para uma lista ou tupla, podemos usar as funções padrão <span>`list(s)`</span> e <span>`tuple(s)` </span> que tomam uma sequência <span>`s`</span> como argumento de entrada e retornar uma lista e tupla, respectivamente:

In [46]:
a = np.array([1, 4, 10])
m = np.array([[1, 2, 3], [4, 5, 6], [9, 7, 8]])
a

array([ 1,  4, 10])

In [47]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [9, 7, 8]])

In [48]:
np.random.test

In [49]:
x=list(a)
print(x)
print(type(x))

[1, 4, 10]
<class 'list'>


In [50]:
y=list(m.reshape((1,9)))
print(y)
print(type(y))
print(len(y))
print(y[0])
print(y[0][1])

[array([1, 2, 3, 4, 5, 6, 9, 7, 8])]
<class 'list'>
1
[1 2 3 4 5 6 9 7 8]
2


In [51]:
z = list(m.reshape((1,9))[0])
print(len(z))
print (z)

9
[1, 2, 3, 4, 5, 6, 9, 7, 8]


In [ ]:
b = np.array(x)
b

In [ ]:
y=tuple(a)
y

In [ ]:
b=np.array(y)
b

### Operações especiais em arrays (alteração de forma e conversão)


Para alterar a forma de um array, temos muitos métodos, como `ravel`, `reshape`, `resize` e atribuir novo valor ao atributo de forma. Os métodos `ravel` e `reshape`,  retornam o argumento (o objeto que chama) com a forma modificada, enquanto o `resize` e a atribuição modificam a matriz real. O método `ravel` transforma a matriz e um vetor, ou seja, uma matriz em uma matriz na linguagem em linguagem C. Ele retorna o argumento como se fosse uma matriz unidimensional, com cada linha sequencialmente organizadas uma a uma.


Vamos discutir o impacto desses métodos com a ajuda do próximo programa. Este programa executa operações de manipulação de forma (`reshape`) em um array bidimensional. A primeira impressão no programa exibirá a matriz original. A função `ravel` mostrará a matriz achatada. A função de impressão após a função `ravel` exibirá a matriz original novamente, como a função `ravel` não altera a matriz original. Agora, a função de `reshape` irá mudar a forma da matriz da forma original (6,3), que tem seis linhas e três colunas, para (3,6), que tem três linhas e seis colunas. Assim, a função de impressão após a função de redimensionamento exibirá a matriz em sua nova forma.

In [ ]:
import numpy as np
x2d = np.array(( (100,200,300),
(111,222,333),
(123,456,789),
(125,457,791),
(127,459,793),
(129,461,795) ))
print('Matriz original = ',x2d)
x2d.ravel()
print('x2d.ravel = ', x2d.ravel())
print('Após ravel = ', x2d)
x2d.resize((3,6))
print('resize para (3,6) = ',x2d)
x2d.reshape(6,3)
print('reshape para (6,3) = ',x2d)
print('Note que reshape não muda a matriz')
Mat=x2d.reshape(6,3)
print('Mat (6,3) = ',Mat)
x2d.shape = (9,2)
print('shape para (9,2) = ',x2d)

In [ ]:
a = np.arange(9).reshape(3,3)
a

In [ ]:
a = np.ndarray((5, 5), dtype=np.float32)
a

In [ ]:
a = np.ndarray((5, 5), dtype=np.uint16)
a

In [ ]:
nlac = 2 # Número de linhas a serem acrescentadas acima
nce = 1 # Número de colunas a serem acrescentadas a esquerda
nlab = 2 # Número de linhas a serem acrescentadas abaixo
ncd = 1 # Número de colunas a serem acrescentadas a esquerda

In [ ]:
np.pad(a, ((nlac, nce), (nlab,ncd)), mode='constant',  constant_values=(5,3))

In [ ]:
? np.pad

Se usarmos np.resize pode-se especificar o tamanho

In [ ]:
a.fill(5)
a

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [9, 7, 8]])
x.resize((3,4))
x

In [ ]:
import numpy as np
 
print ('\n---- De uma lista python para um vetor numpy -----')
lista = []
lista.append(1.0+1j)
lista.append(2.0+5j)
lista.append(3.0-3j)
a = np.array(lista, dtype=np.complex)
print (lista, a, a.dtype, a.shape)
 
print ('\n-------- Usando array --------')
a = np.array([23, 5, 14])
print (a, a.dtype, a.shape)
 
a = np.array([True, False, True])
print (a, a.dtype, a.shape)
 
a = np.array([[1.0, 3.0, 5.0], [7.0, 9.0, 11.0], [13.0, 15.0, 17.0]], dtype=np.float32)
print (a, a.dtype, a.shape)
 
print ('\n-------- Usando arange ----------')
a = np.arange(5,dtype=np.float16)
print (a, a.dtype, a.shape)
 
a = np.arange(15,dtype=np.float16).reshape(3,5)
print (a, a.dtype, a.shape)
 
a = np.arange(1.0, 10.0, 2.0, dtype=np.float)
print (a, a.dtype, a.shape)
 
print ('\n----------- Usando zeros, ones e empty --------------')
a = np.zeros( 5, dtype=np.int32 )
print (a, a.dtype, a.shape)
 
a = np.ones( 5, dtype=np.complex )
print (a, a.dtype, a.shape)
 
a = np.empty( 16, dtype=np.float32 ).reshape(4,4)
print (a, a.dtype, a.shape)
 
print ('\n------ Modificando um elemento da matriz -------')
np.set_printoptions(precision=1)
a[3,3] = 1.0
a[2,1] = 9.0
print (a)

Agora vamos ilustrar algumas operações sobre os vetores:

In [ ]:
import numpy as np
 
#De uma lista python para um vetor numpy
print ('Converte de uma lista para array')
lista = []
lista.append(1.0+1j)
lista.append(2.0+5j)
lista.append(3.0-3j)
a = np.array(lista, dtype=np.complex)
print (lista, a, a.dtype, a.shape)
 
#Usando array
print ('\nUsando Array')
a = np.array([23, 5, 14])
print (a, a.dtype, a.shape)
 
a = np.array([True, False, True])
print (a, a.dtype, a.shape)
 
a = np.array([[1.0, 3.0, 5.0], [7.0, 9.0, 11.0], [13.0, 15.0, 17.0]], dtype=np.float32)
print (a, a.dtype, a.shape)
 
#Usando arange
print ('\nUsando Arange')
a = np.arange(5,dtype=np.float16)
print (a, a.dtype, a.shape)
 
a = np.arange(15,dtype=np.float16).reshape(3,5)
print (a, a.dtype, a.shape)
 
a = np.arange(1.0, 10.0, 2.0, dtype=np.float)
print (a, a.dtype, a.shape)
 
#Usando linspace
print ('\nUsando linspace: gera dados desde inicio ate fim,')
print ('igualmente espaciados, incluindo extremos')
a = np.linspace(0,10,11)
print (a)
a = np.linspace(0,10,41)
print (a)
 
#usando zeros, ones e empty
print ('\nUsando Zeros')
a = np.zeros( 5, dtype=np.int32 )
print (a, a.dtype, a.shape)
 
print ('\nUsando Ones')
a = np.ones( 5, dtype=np.complex )
print (a, a.dtype, a.shape)
 
print ('\nUsando Empty')
a = np.empty( 16, dtype=np.float32 ).reshape(4,4)
print (a, a.dtype, a.shape)
 
np.set_printoptions(precision=2)
print ('\nmodificando um elemento da matriz')
a[3,3] = 1.0
a[2,1] = 9.0
print (a)

## Classes associadas aos arrays

Há um número de classes e subclasses associadas com a classe ndarray. Essas classes são projetadas para oferecer suporte a funcionalidade aprimorada específica. Nos parágrafos seguintes, estaremos discutindo essas classes e subclasses.

### A Sub-classe Matriz

A classe matriz é uma subclasse Python de ndarrays. Uma matriz pode ser criada a partir de outras matrizes ou sequências de caracteres ou qualquer outro objeto que pode ser convertido em um ndarray. A sub-classe da matriz tem operadores especialmente sobregravados, como `*` para a multiplicação da matriz e `**` para a potência da matriz. Várias funções são fornecidas na classe de matriz para executar várias atividades, como classificar elementos, calcular a transposição, encontrar a soma de elementos de matriz, conversão de uma matriz em uma lista e outras estruturas de dados e tipos de dados. Considere o seguinte programa, que define duas matrizes com três linhas e três colunas cada. Por fim, o programa exibe a saída da multiplicação matricial:

In [ ]:
import numpy as np
a = np.matrix('1 2 3; 4 5 6; 7 8 9')
print('A matriz a = ', a)
b = np.matrix('4 5 6; 7 8 9; 10 11 12')
print('A matriz b = ', b)
print('A matriz a*b = ', a*b)

### Máscara de Matriz 

NumPy tem um módulo chamado numpy.ma para criar máscaras para matrizes. Uma matriz mascarada é uma matriz normal que possui algumas entradas inválidas, em falta ou indesejáveis. Tem dois componentes: os ndarrays originais e uma máscara. Uma máscara é uma matriz de valores booleanos usados para determinar se os valores de matriz são válidos ou não. Um valor verdadeiro na máscara reflete que o valor correspondente na matriz é inválido. As entradas mascaradas ou inválidas não serão usadas em qualquer computação adicional em matrizes mascaradas. O próximo programa demonstra o conceito de matrizes mascaradas. Suponha que a matriz original x tem as taxas de pulso de pessoas diferentes e tem duas entradas inválidas. Para mascarar essas entradas inválidas, o valor correspondente é definido como 1 (verdadeiro) na máscara. No final, calculamos a média dos arrays originais e mascarados. Sem mascaramento, a média é 61,1, por causa de dois valores negativos; Após mascaramento, a média dos restantes oito valores é 94,5:

In [64]:
import numpy as np
import numpy.ma as ma
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
mx = ma.masked_array(x, mask=[1, 0, 0, 0, 0, 1, 0, 1, 0, 0])
mx2 = ma.masked_array(x,mask=x<90,fill_value=7)
print(mx)
print('A média é: ', x.mean())
print(mx2)
print('A média com a máscara 1 é: ', mx.mean())
print('A média com a máscara 2 é: ', mx2.mean())

[-- 79 85 90 150 -- 120 -- 60 100]
A média é:  61.1
[-- -- -- 90 150 -- 120 -- -- 100]
A média com a máscara 1 é:  97.71428571428571
A média com a máscara 2 é:  115.0


In [63]:
mx2

masked_array(data=[--, --, --, 90, 150, --, 120, --, --, 100],
             mask=[ True,  True,  True, False, False,  True, False,  True,
                    True, False],
       fill_value=7)

In [65]:
? ma.masked_array

## linspace, funções de matriz e plotagem

O comando **linspace** faz uma matriz linear de pontos de um início para um valor final, conforme iluistrado a seguir

In [ ]:
np.linspace(0,1)

Se você fornecer um terceiro argumento, ele toma isso como o número de pontos no espaço. Se você não fornecer o argumento, ele considera um **espaço linear com 50 pontos igualmente espaçados**. Por exemplo,

In [ ]:
np.linspace(0,1,11)

In [ ]:
x0 = 0
xf = 1
n  = 11
# gera um array x com espaçamento dx= (xf-x0)/(n-1) e n pontos.
x  = np.linspace(x0,xf,n)
x

**linspace** é uma maneira muito fácil de gerar coordenadas para fazer gráficos. Funções na biblioteca numpy (todas importadas para o notebook IPython) podem atuar em um vetor inteiro (ou mesmo em uma matriz) de pontos ao mesmo tempo. Portanto, considere por exemplo que desejamos fazer o gráfico da função *sen(x)* em função de *x* no intervalo de 0 à *2*pi*, para isso, criamos um vetor *x* contendo as coordenadas e um vetor *y* contendo o valor da função *sen(x)* nos respectivos pontos, ou seja

In [ ]:
import numpy as np
n = 101                      # Número de pontos do vetor
x=np.linspace(0,2*np.pi,n)   # Vetor das coordenadas 
y=np.sin(x)                  # Vetor da função 

A seguir, a título de exemplo, vamos fazer um gráfico dessa, função usando biblioteca matplotlib, a qual será explora no próximo tópico [Visualização de dados](#15-Visualizacao-de-dados.ipynb)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt     # Para fazer os gráficos das funções
plt.plot(x, y) 

### Operações de Álgebra Linear Padrão

## Matrizes especiais (numpy.matlib)

A numpy oferece as seguintes matrizes especiais [numpy.matlib](https://docs.scipy.org/doc/numpy/reference/routines.matlib.html), e esse módulo contém todas as funções no espaço para criar matrizes, com as seguintes funções de substituição que retornam matrizes em vez de ndarrays.

Funções que também estão no namespace numpy e as matrizes de retorno:

- *mat(dados [, dtype])* Interpretar a entrada como uma matriz.
- *matrix*  Retorna uma matriz de um objeto tipo matriz, ou de uma sequência de dados.
- *asmatrix(data [, dtype])* Interpreta a entrada como uma matriz.
- *bmat(obj [, ldict, gdict])* Cria um objeto matriz a partir de uma sequência de caracteres, sequência aninhada ou matriz.

Funções de substituição na matlib: 

- *empty(shape [, dtype, order])* Retorna uma nova matriz de dada forma e tipo, sem inicializar entradas.
- *zeros (shape [, dtype, order])* Retorna uma matriz de dado forma e tipo, preenchido com zeros.
- *ones(shape [, dtype, order])* Retorna uma matriz toda preenchida com o valor 1.
- *eye(n [, M, k, dtype])* Retorna uma matriz com uns na diagonal e zeros em outro lugar.
- *identity (n [, dtype])* Retorna a matriz de identidade quadrada de determinado tamanho.
- *repmat(a, m, n)* Repita uma matriz 0-D para 2-D ou matriz MxN vezes.
- *rand(*args)* Retorna uma matriz de valores aleatórios com forma dada.
- *randn(*args)* Retorna uma matriz aleatória com dados da distribuição "normal padrão".

In [67]:
import numpy as np
import numpy.matlib
import numpy.random
n = 4                          # uma das dimensões da matriz quadrada
A = numpy.random.rand(n, n)    # gera uma matriz aleatória de n por n 
x = numpy.random.rand(n)       # gera um vetor aleatório de n elementos
print("A = ", A)
print("x = ", x)
print("Matriz de zeros", np.matlib.zeros((n,n)))
print("Matriz de uns", np.matlib.ones((n,n)))
print("Matriz diagonal 1", np.matlib.eye(n))
print("Matriz de identidade", np.matlib.identity(n))
print("Matriz de aleatória com distribuição normal", np.random.randn(n,n))

A =  [[0.2681025  0.47026866 0.57447789 0.42709956]
 [0.30032088 0.18258276 0.96060387 0.30909469]
 [0.45467215 0.79432553 0.82031606 0.40495133]
 [0.30816531 0.04440232 0.19983782 0.44353084]]
x =  [0.20274738 0.52061162 0.80698092 0.21719787]
Matriz de zeros [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matriz de uns [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matriz diagonal 1 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz de identidade [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz de aleatória com distribuição normal [[-2.36277858  0.38562606  0.84337453 -0.92731709]
 [ 0.23184485  0.65306438 -1.53316927 -0.62202604]
 [ 0.28439711  0.3828443   0.18683302 -1.12544834]
 [-0.4392724   0.25796266  1.25175945 -0.50357211]]


In [70]:
np.random.randint(0,100)

10

Vejam que não é necessário explicitar *import numpy.matlib*, ou seja, 

In [ ]:
import numpy as np
n = 3                       # uma das dimensões da matriz quadrada
A = np.random.rand(n,n)     # gera uma matriz aleatória de n por n 
x = np.random.rand(n)       # gera um vetor aleatório de n elementos
print("A = ", A)
print("x = ", x)
print("Matriz de zeros", np.zeros((n,n)))
print("Matriz de uns", np.ones((n,n)))
print("Matriz diagonal 1", np.eye(n))
print("Matriz de identidade", np.identity(n))
print("Matriz de aleatória com distribuição normal", np.random.randn(n,n))

## Operaçoes matriciais

As matrizes são objetos sensíveis quando multiplicadas por escalares

In [ ]:
0.125*np.matlib.identity(3,'d')

In [ ]:
? np.matlib.identity

assim como a adição de duas matrizes, desde que elas tenham as mesmas dimensões

In [ ]:
np.matlib.identity(2,'d') + np.array([[1,1],[1,2]])

Algo que confunde os usuários do Matlab/Scilab/Octave é que o operador vezes (*) dá multiplicação elemento por elemento ao invés de multiplicação matricial, assim:

In [ ]:
 np.identity(3)*np.ones((3,3))

In [ ]:
np.dot(np.identity(3),np.ones((3,3)))

entretanto, note a diferença

In [ ]:
np.matlib.identity(4)

In [ ]:
A=np.array([[1, 2, 0], [0,1,0], [0,0,1]])
B=np.array([[1, 1, 1], [1,1,1], [1,1,1]])
C=A*B
C

In [ ]:
C=np.mat(A)*np.mat(B)
print("C=",C)
D=np.dot(A,B)
print("D=",D)

In [ ]:
 np.matlib.identity(4)*np.matlib.ones((4,4))

a qual comportam-se como uma multiplicação matricial.


Existem as funções **det** (essa pertence a biblioteca numpy.linalg), **inverse** e **transpose** que fornecem respectivamente o determinate, a inversa e a transposta de uma dada matriz. A função *transpose* pode ser abreviado com ".T" no final de um objeto de matriz, assim:

In [ ]:
import numpy as np
n = 3                       # uma das dimensões da matriz quadrada
np.set_printoptions(precision=3)
A = np.random.randn(n,n)    # gera uma matriz aleatória de n por n 
print("A = ", A)
print("Transposta de A^{-1} =", np.transpose(A))
print("Transposta de A = ",A.T)
print("Determinante de A = ", np.linalg.det(A))
print("Inversa de A = ", np.linalg.inv(A))

In [ ]:
np.linalg.inv(A)*np.mat(A)

In [ ]:
? np.linalg.inv

Há também uma função **diag()** que leva uma lista ou um vetor e coloca-lo ao longo da diagonal de uma matriz quadrada.

In [ ]:
np.diag([1,2,3,4,5])

#### Multiplicação de matrizes

Duas matrizes podem ser multiplicadas da maneira usual de álgebra linear usando <span>`numpy.matrix multiply`</span>. Aqui está um exemplo:

In [75]:
import numpy as np
import numpy.random       
A = numpy.random.rand(5, 5)    # gera uma matriz aleatória de 5 por 5 
x = numpy.random.rand(5)       # gera um vetor aleatório de 5 elementos
b = np.dot(A, x)               # multiplica a matriz A pelo vetor x 
print("O sistema linear é A * x = b")
print("A = ", A)
print("x = ", x, "  b = ",b)

O sistema linear é A * x = b
A =  [[0.32672836 0.47684421 0.39013757 0.8022064  0.04943494]
 [0.08481593 0.0709188  0.11997392 0.23679607 0.30911456]
 [0.45291481 0.79621453 0.07334077 0.4438445  0.38040527]
 [0.76378098 0.39742673 0.61620944 0.03697793 0.11470753]
 [0.66963997 0.07892333 0.12449915 0.26198466 0.50645361]]
x =  [0.61514831 0.38256612 0.12078911 0.75832286 0.8220369 ]   b =  [1.07950401 0.52746849 1.24135785 0.81864701 1.07215194]


#### Solução de sistemas de equações lineares

Para resolver um sistema de equações *A***x** = **b** que é dado em forma de matriz (*isto é* *A* é uma matriz e **x** e **b** são vetores, onde *A* e **b** são conhecidos e queremos encontrar o vetor desconhecido **x**), podemos usar o pacote de álgebra linear (<span>`linalg`</span>) de <span>`Numpy`</span>:

In [76]:
import numpy.linalg as LA
x = LA.solve(A, b)
print(x)

[0.61514831 0.38256612 0.12078911 0.75832286 0.8220369 ]


In [ ]:
dir(LA)

In [ ]:
? np.linalg.solve

In [73]:
# Solve the system of equations ``3 * x0 + x1 = 9`` and ``x0 + 2 * x1 = 8``:

a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
print(x)
# solução array([ 2.,  3.])

#Check that the solution is correct:

np.allclose(np.dot(a, x), b)

[2. 3.]


True

#### Cálculo de autovetores e autovalores

Aqui está um pequeno exemplo que calcula os autovetores e os autovalores da matriz de identidade (<span>`eye`</span>):

In [77]:
import numpy
import numpy.linalg as LA
A = numpy.eye(3)     #'eye'->I->1 (Todos os elementos da diagonal principal são 1, e os outros 0)
A= numpy.random.rand(3, 3) 
print(A)

[[0.68147107 0.98747411 0.40782312]
 [0.51737319 0.38131264 0.36471199]
 [0.90008039 0.08567736 0.13188708]]


In [78]:
evalues, evectors = LA.eig(A)
print(evalues)

[ 1.57701081+0.j         -0.19117001+0.23919774j -0.19117001-0.23919774j]


In [79]:
print(evectors)

[[ 0.73754822+0.j         -0.29280764+0.25620214j -0.29280764-0.25620214j]
 [ 0.46771015+0.j         -0.15747426-0.29733583j -0.15747426+0.29733583j]
 [ 0.48710352+0.j          0.85756481+0.j          0.85756481-0.j        ]]


Observe que cada um desses comandos fornece sua própria documentação. Por exemplo, <span> `help(LA.eig)` </span> irá dizer-lhe tudo sobre a função de autovetor e autovalor (depois de ter importado `numpy.linalg` como `LA`).

#### Ajuste polinômial de curvas (fitting)

Vamos supor que temos dados x-y para os quais desejamos ajustar por uma curva (minimizando o menor desvio quadrático para ajustar via os dados).


A numpy fornece a rotina <span>`polyfit(x, y, n)`</span> (que é semelhante à função `polyfit` do Matlab que toma uma lista <span>`x`</span> de valores x dos dados, uma lista <y> de valores y dos mesmos dados e uma ordem desejada do polinômio a que será usada para ajustar os dados via mínimos-quadrados, tanto quanto possível.


In [ ]:
%matplotlib inline
import numpy

# Curva demo para o ajuste "fitting": xdata e ydata são os dados de entrada
xdata = numpy.array([0.0 , 1.0 , 2.0 , 3.0 , 4.0 , 5.0])
ydata = numpy.array([0.0 , 0.8 , 0.9 , 0.1 , -0.8 , -1.0])
# Agora para ajustar via um polinômio de terceiro grau (ordem = 3)
z = numpy.polyfit(xdata, ydata, 3)
# z é um array dos coeficientes, o mais alto primeiro, isto é, 
#                 X^3            X^2          X             0
# z = array ([ 0.08703704 , -0.81349206 , 1.69312169 , -0.03968254])
# É conveniente usar os objetos ‘poly1d‘ para tratar com polinômios: 
p = numpy.poly1d(z) # cria uma função polinômial p a partir dos coeficientes
                    # e então p poderá ser calculado para todos os valores de x.

# cria um gráfico "plot"
xs = [0.1 * i for i in range (50)]
ys = [p ( x ) for x in xs]   # calcula p(x) para todos os x na lista xs

import pylab
pylab.plot(xdata, ydata, 'o', label='Dados')
pylab.plot(xs, ys, label='Curve ajustada')
pylab.ylabel('y')
pylab.xlabel('x')
pylab.legend()

In [ ]:
help(pylab.plot)

Isto mostra a curva ajustada (linha contínua) juntamente com os pontos de dados precisos calculados.

## Números aleátorios

 Por números aleatórios entendemos números que pertence a uma série de número os quais se caraterizam por não apresentam nenhum tipo de correlação entre eles, por exemplo, dado o $n-esimo$ elemento de uma dada série, os números prévios a ele não permitem determinar este de forma precisa. Obviamente esta definição é bem simples e minimalista já que a área da matemática que trata do problema é ampla.

No caso dos computadores a forma comum de gerar um número aleatórios é utilizando uma função matemática que gera um número *pseudoaleatórios*. Esses números são pseudoaleatórios porque a função (algoritmo) que gera eles são funções periódicas (não harmônicas), a função só consegue gerar $2^k-1$ números (onde é tipicamente $k=32$ ou $64$) totalmente aleatórios, não é infinita, assim se você gerar mais números do que o período ($2^k-1$) você gerará números que são os mesmo já previamente gerados (assim correlacionados).

Como os geradores de números aleatórios são funções (algoritmos) você tem que dar um valor chamado semente (seed) para ele devolver o número aleatório (tipo você tem que dar o $x$ para ter o $f(x)$, no caso dos geradores $x$ é um inteiro e $f(x)$ é um float), por sorte você sempre tem que dar o mesmo número durante o uso do gerador dentro do seu programa já que o gerador gera o número aleatório e uma nova semente, se você chama o gerador com a mesma semente inicial ele reconhece e utiliza aquela que tinha gerado.

O algoritmo utilizado no numpy para gerar números aleatórios é o algoritmo Mersenne Twister. Para demostrar seu uso o seguente programa vari gerar um conjunto de 20 números aleatórios distribuídos de forma uniforme: 

In [ ]:
import numpy as np
 
xi       = 0.0
xf       = 1.0
numDados = 2
semente  = 938284
 
#iniciando o gerador
conjAleaNum = np.random.RandomState(seed=semente)
 
#gerando os números
print ('números gerados com a semente ', semente, ":")
a = conjAleaNum.uniform(low=xi, high=xf, size=numDados)
print (a, "\n")
 
print ('outros números gerados sem modificar a semente ', semente, ":")
b = conjAleaNum.uniform(low=xi, high=xf, size=numDados)
print (b, "\n")
 
print ('outros números gerados modificando a semente para ', semente, ":")
conjAleaNum = np.random.RandomState(seed=semente)
c = conjAleaNum.uniform(low=xi, high=xf, size=2*numDados)
print (c, "\n")
 
print ('o dobro de números gerados modificando a semente para ', semente, ":")
conjAleaNum = np.random.RandomState(seed=semente)
d = conjAleaNum.uniform(low=0.0, high=xf, size=2*numDados)
print (d)

semente  = 738285

print ('\n o dobro de números gerados modificando a semente para ', semente, ":")
conjAleaNum = np.random.RandomState(seed=semente)
d = conjAleaNum.uniform(low=0.0, high=xf, size=2*numDados)
print (d)

Neste exemplo devemos prestar atenção nos seguintes detalhes, na linha 12 foi criado uma variável (objeto) chamado conjAleaNum (), essa variável é o conjunto conjunto dos números aleatórios que foi inicializado com a semente semente. Na linha 16 retiramos numDados elementos do conjunto (10 no exemplo) que estejam no intervalo $[low=xi, high=xf)$ - inclui $xi$ mas não $xf$ - e são armazenados no vetor a. Na linha 20 são retirados outros numDados elementos do conjunto e na linha 25 se repete o mesmo procedimento, contudo observe que na linha 24 se reinicio o conjunto de números aleatorios ao chamar a função np.random.RandomState(seed=semente). A prova disto é que no resultado o primeiro grupo de numDados é diferente do II grupo mas igual ao terceiro. Melhor ainda, para mostrar que conjAleaNum é uma secuencia contínua de dados, na linha 29 se reinicia a sequencia e se extra 2 vezes conjAleaNum e o conjunto resultante é a união dos I e II grupo que foram retirados.

## Tipo de distribuições

No exemplo acima vemos que os números são retirados de forma a estarem uniformemente distribuídos, o que significa isso? Para entender teremos que fazer um gráfico de N=100 valores sorteados os quais serão colhidos de uma distribuição uniforme entre -1 e 1. 

O código acima gerou 1000 pontos entre -1 e 1, a pergunta agora é qual é a probabilidade de encotrar um número entre 0.1 e 0.2? Para responder isso devemos dividir o intervalo $[-1,1)$ em pequenos intevalinhos de tamanho 0.1 e contar quantos números caim nesse no intervalo que queremos (no caso entre 0.1 e 0.2), afortunadamente isto é relativamente simples utilizando matplotlib, basta utilizar a função hist e pedir que seja feito 20 intervalos ($(1.0 - (-1.0))/0.1 = 20$): 

In [ ]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
 
xi       = -1.0
xf       = 1.0
numDados = 1000
semente  = 4727
 
#iniciando o gerador
conjAleaNum = np.random.RandomState(seed=semente)
 
#gera os número
y = conjAleaNum.uniform(low=xi, high=xf, size=numDados)
 
#cria numDados entre 0 e numDados igualmente espaçados
x = np.linspace(1, numDados, numDados)
 
#cria o gráfico
plt.plot(x, y, '-')
plt.show()

In [ ]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
 
xi       = -1.0
xf       = 1.0
numDados = 1000
semente  = 4727
 
#iniciando o gerador
conjAleaNum = np.random.RandomState(seed=semente)
 
#gera os número
y = conjAleaNum.uniform(low=xi, high=xf, size=numDados)
 
#cria numDados entre 0 e numDados igualmente espaçados
x = np.linspace(1, numDados, numDados)
 
plt.hist(y, bins=30)
plt.show()

Da figura vemos que algo perto de 40 dos 1000 números estão entre 0.1 e 0.2, mas note que quase todos estão dentro dessa faixa, de fato, se nos aumentamos para $1\times10^6$ a quantidade de número teremos as figura abaixo 

In [ ]:
#Basta alterar o valor do número de dados
numDados=int(1e6)

#iniciando o gerador
conjAleaNum = np.random.RandomState(seed=semente)
 
#gera os número
y = conjAleaNum.uniform(low=xi, high=xf, size=numDados)
 
#cria numDados entre 0 e numDados igualmente espaçados
x = np.linspace(1, numDados, numDados)
 
plt.hist(y, bins=50)
plt.show()

De onde vemos que os números se distribuem uniformemente no intervalo isto é, temos a mesma probabilidade de encontrar um número em qualquer seção do intervalo.

A outra distribuição muito utilizada em física é a distribuição gaussiana ou normal que tem a forma funcional: \[ p(x) = \frac{1}{\sqrt{ 2 \pi \sigma^2 }} e^{ - \frac{ (x - \mu)^2 } {2 \sigma^2} } \nonumber \] onde $\sigma$ é a largura da gaussiana e $\mu$ onde ela está centrada. O script a seguir mostra como implementar com numpy a geração de pontos que respeitem o comportamento gaussiano: 

In [ ]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
 
centro   = 0.0
largura  = 1.0
numDados = 1000
semente  = 4727
 
#iniciando o gerador
conjAleaNum = np.random.RandomState(seed=semente)
 
#gera os número
y = conjAleaNum.normal(loc=centro, scale=largura, size=numDados)
 
#cria numDados entre 0 e numDados igualmente espaçados
x = np.linspace(1, numDados, numDados)
 
plt.hist(y, bins=20)
plt.show()

Aumentando a quantidade de dados a ser gerada para um milhão e colocando o bins=100 o resultado é 

In [ ]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
 
centro   = 0.0
largura  = 1.0
numDados = int(1e6)
semente  = 4727
 
#iniciando o gerador
conjAleaNum = np.random.RandomState(seed=semente)
 
#gera os número
y = conjAleaNum.normal(loc=centro, scale=largura, size=numDados)
 
#cria numDados entre 0 e numDados igualmente espaçados
x = np.linspace(1, numDados, numDados)

# Aumentou-se a quantidade de bins=100
plt.hist(y, bins=100)
plt.show()

Além dessas duas distribuições a numpy define varias outras, como a poisson pode ser visto no [site do numpy seção de números aleatórios](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState)  <https://docs.scipy.org/doc/numpy/reference/routines.random.html>. 

Mínimo quadrados [via scipy](https://python4mpia.github.io/fitting_data/least-squares-fitting.html)

In [ ]:
import numpy,math
import scipy.optimize as optimization
import matplotlib.pyplot as plt

# Chose a model that will create bimodality.
def func(x, a, b):
    return a + b*b*x  # Term b*b will create bimodality.

# Create toy data for curve_fit.
xdata = numpy.array([0.0,1.0,2.0,3.0,4.0,5.0])
ydata = numpy.array([0.1,0.9,2.2,2.8,3.9,5.1])
sigma = numpy.array([1.0,1.0,1.0,1.0,1.0,1.0])

# Compute chi-square manifold.
Steps = 101  # grid size
Chi2Manifold = numpy.zeros([Steps,Steps])  # allocate grid
amin = -7.0  # minimal value of a covered by grid
amax = +5.0  # maximal value of a covered by grid
bmin = -4.0  # minimal value of b covered by grid
bmax = +4.0  # maximal value of b covered by grid
for s1 in range(Steps):
    for s2 in range(Steps):
        # Current values of (a,b) at grid position (s1,s2).
        a = amin + (amax - amin)*float(s1)/(Steps-1)
        b = bmin + (bmax - bmin)*float(s2)/(Steps-1)
        # Evaluate chi-squared.
        chi2 = 0.0
        for n in range(len(xdata)):
            residual = (ydata[n] - func(xdata[n], a, b))/sigma[n]
            chi2 = chi2 + residual*residual
        Chi2Manifold[Steps-1-s2,s1] = chi2  # write result to grid.

# Plot grid.
plt.figure(1, figsize=(8,4.5))
plt.subplots_adjust(left=0.09, bottom=0.09, top=0.97, right=0.99)
# Plot chi-square manifold.
image = plt.imshow(Chi2Manifold, vmax=50.0,
              extent=[amin, amax, bmin, bmax])
# Plot where curve-fit is going to for a couple of initial guesses.
for a_initial in -6.0, -4.0, -2.0, 0.0, 2.0, 4.0:
    # Initial guess.
    x0   = numpy.array([a_initial, -3.5])
    #xFit = optimization.leastsq(func, x0, xdata, ydata, x0, sigma)[0]
    xFit = optimization.curve_fit(func, xdata, ydata, x0, sigma)[0]
    plt.plot([x0[0], xFit[0]], [x0[1], xFit[1]], 'o-', ms=4,
                 markeredgewidth=0, lw=2, color='orange')
plt.colorbar(image)  # make colorbar
plt.xlim(amin, amax)
plt.ylim(bmin, bmax)
plt.xlabel(r'$a$', fontsize=24)
plt.ylabel(r'$b$', fontsize=24)
plt.savefig('demo-robustness-curve-fit.png')
plt.show()

In [ ]:
? optimization.leastsq

## Exercícios

1. Escreva um programa que realize o produto de duas matrizes: $C = AB$. O programa deve perguntar para o usuário o número de linhas e colunas de cada matriz. Deve checar, utilizando o dado anterior, se o produto pode ser realizado efetivamente. Deve ler do teclado cada uma das matrizes e realizar seu produto segundo a equação $c_{ij} = \sum_{k=1}^{q} a_{ik}b_{kj}$. Como exemplo teste seu programa utilizando

    $$\displaystyle{ \left[\begin{array}{c c c} 1 & 2 & 4 \\ 2 & 6 & 0 \end{array}\right] \; \left[\begin{array}{c c c c} 4 & 1 & 4 & 3 \\ 0 & -1 & 3 & 1 \\ 2 & 7 & 5 & 2 \end{array}\right] = \left[\begin{array}{c c c c} 12 & 27 & 30 & 13 \\ 8 & -4 & 26 & 12 \end{array}\right] }$$
    
2. Existe um teorema matemática que permite calcular as novas coordenadas de um vetor após ter sido realizada uma rotação em torno de um vetor unitário $\vec u$. Esse teorema diz que: Se $\vec u = a\hat i+b\hat j+c\hat k$ é um vetor unitário, então a matriz canônica $R_{\vec u , \theta}$ da rotação pelo ângulo $\theta$ em torno do eixo pela origem com orientação $\vec u$ é dada por

    $$\displaystyle{ R_{\vec u , \theta} = \left[\begin{array}{c c c} a^2\left(1-\cos\theta\right)+\cos\theta & ab\left(1-\cos\theta\right)-c\sin\theta & ac\left(1-\cos\theta\right)+b\sin\theta \\ ab\left(1-\cos\theta\right)+c\sin\theta & b^2\left(1-\cos\theta\right)+\cos\theta & bc \left(1-\cos\theta\right)-a\sin\theta \\ ac\left(1-\cos\theta\right)-b\sin\theta & bc \left(1-\cos\theta\right)+a\sin\theta & c^2\left(1-\cos\theta\right)+\cos\theta \end{array}\right] }$$
    Dessa forma dado um vetor $\vec r$ o novo vetor que se obtêm apôs a rotação de $\theta$ em torno de $\vec u$ é o vetor $\vec r'$ dado por: $\vec r' = R_{\vec u , \theta} \vec r$. De posse desse teorema, construa um programa que:

    1. Pergunte a coordenada de um ponto, no espaço $(x,y,z)$, que permita traçar uma reta desde a origem, suporemos que o vetor unitário está sobre essa reta
    2. Pergunte as coordenadas do vetor que quer ser rotado
    3. Pergunte o ângulo de rotação, em graus (a matriz de rotação é em radianos)
    4. Como resultado o programa deve devolver o novo vetor resultante da rotação

    Como teste considere o ponto de referencia para o vetor unitário $(1,1,1)$, uma rotação de $120^\circ$ e o vetor a ser rotado é $\vec r = \hat i - \hat j$. O resultado dessa operação é o novo vetor $\vec r' = \hat j - \hat k$. 


### Mais exemplos da numpy …

- …podem ser encontrados aqui: <http://www.scipy.org/Numpy_Example_List>

- [NumPy: creating and manipulating numerical data](http://www.scipy-lectures.org/intro/numpy/numpy.html)

- [100 numpy exercises](https://github.com/rougier/numpy-100)

### Numpy para usuários Matlab 

Existe uma página web dedicada que explica Numpy a partir da perspectiva de um (experiente) usuário Matlab em https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.